#see https://github.com/codecov/support/wiki/Codecov-Yaml
codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 0  # 2 = xx.xx%, 0 = xx%
  round: nearest # how coverage is rounded: down/up/nearest
  range: 40...90 # custom range of coverage colors from red -> yellow -> green
  status:
    # https://codecov.readme.io/v1.0/docs/commit-status
    project:
      default:
        against: auto
        target: 60% # specify the target coverage for each commit status
        threshold: 15% # allow this little decrease on project
        # https://github.com/codecov/support/wiki/Filtering-Branches
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    patch: off
    changes: false

comment:
  layout: header, diff
  require_changes: false
  behavior: default  # update if exists else create new
  branches: *