# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

language: python

sudo: false

env:
  global:
    - CC_TEST_REPORTER_ID=53c61165ba2bd222535555616b6eb9fa540787f53e5f93be710c9a3c183eb868

python:
  - 2.7
  #- 3.4  # will be deprecated for pandas
  - 3.5
  - 3.6
  # - "3.7-dev"

# See http://docs.travis-ci.com/user/caching/#pip-cache
cache: pip

before_install:
  - pip install --upgrade pip

install:
  - pip install -r requirements.txt
  - pip install nose coverage codecov pytest codacy-coverage

before_script:
  - mkdir output
  - gcc --version ; python --version ; pip --version ; pwd ; ls -l
  # code coverage tool
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
#  - pytest -v --doctest-modules
  - nosetests -v --exe --with-doctest --with-xunit --with-coverage --cover-package=handlers  # --ignore-files=*.ijm

  - python handlers/run_evaluate_landmarks.py -a ./annotations -o ./output
  - python handlers/run_generate_landmarks.py -a ./annotations -d ./dataset --scales 5
  - python handlers/run_visualise_landmarks.py -l ./dataset -i ./dataset -o ./output

after_success:
  - codecov  # public repository on Travis CI
  - coverage xml
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
  - coverage report
