# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

dist: xenial  # Ubuntu 16.04

language: python

sudo: false

env:
  global:
    - CC_TEST_REPORTER_ID=53c61165ba2bd222535555616b6eb9fa540787f53e5f93be710c9a3c183eb868
    - CODACY_PROJECT_TOKEN=f15c407623e8407e88c9ca5e50470562

python:
  - 2.7
  # - 3.4  # will be deprecated for pandas
  - 3.5
  - 3.6
  - 3.7

# See http://docs.travis-ci.com/user/caching/#pip-cache
cache: pip

before_install:
  - pip install --upgrade pip

install:
  - sudo apt-get install python-opencv
  - pip install -r requirements.txt
  - pip install -U coverage pytest pytest-cov codecov codacy-coverage flake8
  # code coverage tool
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

before_script:
  - mkdir output
  - python --version ; pwd ; ls -l
  - ./cc-test-reporter before-build
  - pip --version ; pip freeze

script:
#  - nosetests -v --exe --with-doctest --with-xunit --with-coverage --cover-package=handlers  # --ignore-files=*.ijm
  - coverage run --source handlers -m py.test handlers -v --doctest-modules --junitxml=pytest_junit.xml
  - flake8 . --ignore=E402 --max-line-length=100

  - python handlers/run_evaluate_landmarks.py -a ./annotations -o ./output --visual
  - python handlers/run_generate_landmarks.py -a ./annotations -d ./dataset --scales 5
  - python handlers/run_visualise_landmarks.py -l ./dataset -i ./dataset -o ./output

after_success:
  - codecov  # public repository on Travis CI
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - coverage report
