# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

language: python

sudo: false

python:
  - 2.7
  #- 3.4  # will be deprecated for pandas
  - 3.5
  - 3.6
  # - "3.7-dev"

# See http://docs.travis-ci.com/user/caching/#pip-cache
cache: pip

before_install:
  - pip install --upgrade pip

install:
  - pip install -r requirements.txt
  - pip install nose coverage codecov pytest codacy-coverage

before_script:
  - mkdir output
  - gcc --version ; python --version ; pip --version ; pwd ; ls -l

script:
#  - pytest -v --doctest-modules
  - nosetests -v --exe --with-doctest --with-xunit --with-coverage --cover-package=scripts  # --ignore-files=*.ijm

after_success:
  - codecov  # public repository on Travis CI
  # private repository on Travis CI
  # - codecov -t XXXXXXXXXXXXXXXXXXXXXX
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - coverage report
